===========================================================================
Type: Info
Date: 2020-12-26 02:19:53.476
Message: Product excel report generated
===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 03:46:11.306
Message: First Level Message: An error occurred while updating the entries. See the inner exception for details.
Second Level Message: Cannot insert the value NULL into column 'CompanyName', table 'Inventory-Asp-Core-MVC-Ajax.dbo.Suppliers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
StackTrace:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at AspNetCore.Lib.Services.Repository`1.<CommitAsync>b__8_0() in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Services\Repository.cs:line 49
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass6_0.<<Add>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 03:50:29.209
Message: Supplier Added: (hi - 323 - 00809 - True - poipoi
  )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 03:56:55.091
Message: Supplier Added: (opop - 0909 - 909 - True - jkjl  )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 03:57:48.042
Message: Supplier Added: (yiuy - uiou - iou - True - iuoi  )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 03:59:08.522
Message: Supplier Added: (yiu - 798 - uyiu - True - uyiu  )
===========================================================================
===========================================================================
Type: Warn
Date: 2020-12-26 04:00:08.397
Message: Supplier Deleted: Id=60 CompanyName=yiu
===========================================================================
===========================================================================
Type: Warn
Date: 2020-12-26 04:00:12.029
Message: Supplier Deleted: Id=59 CompanyName=yiuy
===========================================================================
===========================================================================
Type: Warn
Date: 2020-12-26 04:00:35.917
Message: Supplier Deleted: Id=58 CompanyName=opop
===========================================================================
===========================================================================
Type: Warn
Date: 2020-12-26 04:00:41.407
Message: Supplier Deleted: Id=57 CompanyName=uuuu
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 04:00:52.512
Message: Supplier Edited: (ytyt - ii* -  - False -   )
===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 04:03:09.677
Message: First Level Message: An error occurred while updating the entries. See the inner exception for details.
Second Level Message: Cannot insert the value NULL into column 'Phone', table 'Inventory-Asp-Core-MVC-Ajax.dbo.Suppliers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
StackTrace:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at AspNetCore.Lib.Services.Repository`1.<CommitAsync>b__8_0() in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Services\Repository.cs:line 49
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass6_0.<<Add>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 04:04:01.706
Message: Supplier Added: (hiuyui - 87878 -  - False -   )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 04:06:32.985
Message: Supplier Added: (yuiy - 687678 -  - False -   )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 04:07:21.344
Message: Supplier Added: (ygyhgy - 87789 -  - False -   )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 04:11:40.621
Message: Supplier Added: (yiuy - 8798 -  - False -   )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 05:18:53.483
Message: Supplier Added: (yyytt - 7687687 -  - False -   )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 05:48:12.171
Message: Supplier Added: (uyiuy - uytyu -  - False -   )
===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 06:17:05.381
Message: First Level Message: An error occurred while updating the entries. See the inner exception for details.
Second Level Message: Cannot insert the value NULL into column 'Phone', table 'Inventory-Asp-Core-MVC-Ajax.dbo.Suppliers'; column does not allow nulls. INSERT fails.
The statement has been terminated.
StackTrace:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at AspNetCore.Lib.Services.Repository`1.<CommitAsync>b__8_0() in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Services\Repository.cs:line 49
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass6_0.<<Add>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 06:31:28.396
Message: First Level Message: An error occurred while updating the entries. See the inner exception for details.
Second Level Message: Cannot insert duplicate key row in object 'dbo.Suppliers' with unique index 'IX_Suppliers_CompanyName'. The duplicate key value is (Datagene).
The statement has been terminated.
StackTrace:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at AspNetCore.Lib.Services.Repository`1.<CommitAsync>b__8_0() in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Services\Repository.cs:line 49
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass6_0.<<Add>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 07:19:11.360
Message: Supplier Added: (Datagener - 87987 - 8798 - False -   )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 07:21:26.031
Message: Supplier Added: (ytuyt - 9879 - yti - False -   )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 07:22:02.473
Message: Supplier Added: (uoiui - 980 -  - False -   )
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 07:33:07.335
Message: Supplier Added: (rtyr - 878 -  - False -   )
===========================================================================
===========================================================================
Type: Warn
Date: 2020-12-26 07:33:17.478
Message: Supplier Deleted: Id=73 CompanyName=rtyr
===========================================================================
===========================================================================
Type: Warn
Date: 2020-12-26 07:39:26.694
Message: Supplier Deleted: Id=72 CompanyName=uoiui
===========================================================================
===========================================================================
Type: Info
Date: 2020-12-26 07:40:59.441
Message: Supplier Added: (joijpi - 89098 -  - False -   )
===========================================================================
===========================================================================
Type: Warn
Date: 2020-12-26 07:41:06.786
Message: Supplier Deleted: Id=74 CompanyName=joijpi
===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:44:47.804
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:45:27.805
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:47:30.103
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:47:57.109
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:48:57.399
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:49:15.008
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:49:56.026
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:51:07.014
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:52:12.248
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:52:31.490
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 07:57:54.534
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 08:02:03.462
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Warn
Date: 2020-12-26 08:05:38.388
Message: Supplier Deleted: Id=67 CompanyName=uyiuy
===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 08:08:25.669
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 08:11:50.882
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 08:12:56.175
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 08:13:03.565
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 08:15:26.560
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 08:15:58.877
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
===========================================================================
Type: Exception
Date: 2020-12-26 08:17:52.420
Message: First Level Message: Exception of type 'System.Exception' was thrown.
StackTrace:    at Inventory_Asp_Core_MVC_Ajax.Businesses.Classes.SupplierBiz.<>c__DisplayClass8_0.<<Delete>b__0>d.MoveNext() in C:\Users\ramin\source\repos\Inventory-Asp-Core-MVC-Ajax\Inventory-Asp-Core-MVC-Ajax\Businesses\Classes\SupplierBiz.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at AspNetCore.Lib.Models.Result.TryAsync(Func`1 func, Action onException) in C:\Users\ramin\source\repos\AspNetCore.Lib.V3.1.9\AspNetCore.Lib\Models\Result.cs:line 74

===========================================================================
